import type { Metadata } from "next";
import "./globals.css";
import ParallaxProviderwarper from "@/components/warpers/ParallaxProviderwarper";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavBar />
        <ParallaxProviderwarper>{children}</ParallaxProviderwarper>

        <Footer />
      </body>
    </html>
  );
}
